# Generated by Django 4.2.2 on 2023-06-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LoadedCost", "0002_remove_employee_hourly_rate_remove_employee_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
