# Generated by Django 4.2.2 on 2023-06-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LoadedCost", "0003_employee_hourly_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
    ]
